"use client";
import { useEffect, useState } from "react";
import { CalendarDays, LoaderCircle } from "lucide-react";
import { PageHeading } from "@/components/ui/page-heading";

type Period={status:string;assignments:{id:string;date:string;status:string;employee:{name:string};shift:{name:string}|null}[]}|null;
export default function SchedulePage(){const now=new Date();const [year,setYear]=useState(now.getFullYear());const [month,setMonth]=useState(now.getMonth()+1);const [period,setPeriod]=useState<Period>(null);const [loading,setLoading]=useState(false);const [message,setMessage]=useState("");
 const load=()=>fetch(`/api/schedule?year=${year}&month=${month}`).then(r=>r.json()).then(setPeriod);
 useEffect(()=>{void fetch(`/api/schedule?year=${year}&month=${month}`).then(r=>r.json()).then(setPeriod)},[year,month]);
 async function generate(){setLoading(true);setMessage("");const r=await fetch("/api/schedule",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({year,month})});const body=await r.json();setMessage(r.ok?`Schedule generated${body.warnings?.length?` with ${body.warnings.length} coverage warning(s)`:" successfully"}.`:body.error);await load();setLoading(false)}
 const working=period?.assignments.filter(a=>a.status==="WORKING")??[];const grouped=Object.groupBy(working,a=>a.date.slice(0,10));
 return <div className="mx-auto max-w-7xl"><PageHeading eyebrow="Workforce planning" title="Schedule Generator" description="Generate a monthly roster from your team, shifts, leave, preferences, and coverage rules."/><div className="mb-6 flex flex-wrap items-end gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="text-sm font-semibold">Month<select value={month} onChange={e=>setMonth(Number(e.target.value))} className="mt-2 block rounded-xl border border-slate-200 px-4 py-3">{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{new Date(2020,i).toLocaleString("en",{month:"long"})}</option>)}</select></label><label className="text-sm font-semibold">Year<input value={year} onChange={e=>setYear(Number(e.target.value))} type="number" className="mt-2 block w-28 rounded-xl border border-slate-200 px-4 py-3"/></label><button disabled={loading} onClick={generate} className="flex items-center gap-2 rounded-xl bg-orange-500 px-5 py-3 font-bold text-white">{loading?<LoaderCircle className="h-4 w-4 animate-spin"/>:<CalendarDays className="h-4 w-4"/>}Generate schedule</button></div>{message&&<p className="mb-5 rounded-xl bg-blue-50 p-4 text-sm font-semibold text-blue-700">{message}</p>}{!period?<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-14 text-center text-slate-500">No schedule exists for this month yet.</div>:<div><p className="mb-4 text-sm font-semibold text-slate-500">Status: {period.status} · {working.length} working assignments</p><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Object.entries(grouped).map(([date,items])=><article key={date} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">{new Date(`${date}T12:00:00`).toLocaleDateString("en",{weekday:"long",month:"short",day:"numeric"})}</h2><div className="mt-4 space-y-2">{items?.map(a=><div key={a.id} className="flex justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><b>{a.employee.name}</b><span className="text-slate-500">{a.shift?.name}</span></div>)}</div></article>)}</div></div>}</div>}
