import { Activity, AlertTriangle, CalendarCheck, CheckCircle2, Clock3, Users } from "lucide-react";
import { PageHeading } from "@/components/ui/page-heading";

const stats = [
  { label: "Working today", value: "—", helper: "From the approved schedule", icon: Users, color: "text-blue-600 bg-blue-50" },
  { label: "Coverage", value: "—", helper: "Across all active shifts", icon: Activity, color: "text-emerald-600 bg-emerald-50" },
  { label: "Tasks assigned", value: "—", helper: "For today's roster", icon: CheckCircle2, color: "text-violet-600 bg-violet-50" },
  { label: "Next Slack post", value: "—", helper: "Configure in Settings", icon: Clock3, color: "text-orange-600 bg-orange-50" },
];

export default function OverviewPage() {
  return <div className="mx-auto max-w-7xl"><PageHeading eyebrow="Operations overview" title="Good morning" description="A clear view of today's staffing, task readiness, and Slack delivery." /><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, helper, icon: Icon, color }) => <article key={label} className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm"><div className={`mb-5 flex h-10 w-10 items-center justify-center rounded-xl ${color}`}><Icon className="h-5 w-5" /></div><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold tracking-tight text-slate-950">{value}</p><p className="mt-2 text-xs text-slate-400">{helper}</p></article>)}</section><section className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><article className="rounded-3xl border border-slate-200/80 bg-white p-6 shadow-sm"><div className="mb-6 flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Today&apos;s readiness</h2><p className="mt-1 text-sm text-slate-500">Complete these steps before posting the roster.</p></div><CalendarCheck className="h-5 w-5 text-orange-500" /></div><div className="space-y-3">{["Approve the monthly schedule", "Assign daily task categories", "Review breaks and notes", "Verify the Slack channel"].map((item, index) => <div key={item} className="flex items-center gap-3 rounded-xl border border-slate-100 bg-slate-50/70 px-4 py-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-white text-xs font-bold text-slate-500 shadow-sm">{index + 1}</span><span className="text-sm font-semibold text-slate-700">{item}</span></div>)}</div></article><article className="rounded-3xl bg-slate-950 p-6 text-white shadow-xl shadow-slate-300/50"><AlertTriangle className="mb-6 h-7 w-7 text-orange-400" /><h2 className="text-xl font-bold">Setup required</h2><p className="mt-2 text-sm leading-6 text-slate-400">Add your team, shifts, staffing rules, and Slack credentials. This panel will then show live coverage warnings.</p><div className="mt-8 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full w-1/5 rounded-full bg-orange-500" /></div><p className="mt-3 text-xs font-semibold text-slate-500">Foundation ready</p></article></section></div>;
}
