"use client";
import { FormEvent, useEffect, useState } from "react";
import { Bell, Clock3, Plus } from "lucide-react";
import { PageHeading } from "@/components/ui/page-heading";

type Data = { settings: { timezone:string; postTime:string; slackChannelId:string; automationEnabled:boolean; maxConsecutiveDays:number }; shifts:{id:string;name:string;startTime:string;endTime:string;staffingRules:{minimumStaff:number;minimumBilingual:number}[]}[]; slackConfigured:boolean };
export default function SettingsPage(){
 const [data,setData]=useState<Data|null>(null); const [message,setMessage]=useState("");
 const load=()=>fetch("/api/settings").then(r=>r.json()).then(setData);
 useEffect(()=>{void fetch("/api/settings").then(r=>r.json()).then(setData)},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({timezone:f.get("timezone"),postTime:f.get("postTime"),slackChannelId:f.get("channel"),automationEnabled:f.get("automation")==="on",maxConsecutiveDays:Number(f.get("maxDays"))})});setMessage(r.ok?"Settings saved successfully.":"Could not save settings.");await load()}
 async function addShift(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const r=await fetch("/api/shifts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name"),startTime:f.get("start"),endTime:f.get("end"),minimumStaff:Number(f.get("staff")),minimumBilingual:Number(f.get("bilingual"))})});setMessage(r.ok?"Shift added successfully.":(await r.json()).error);if(r.ok)form.reset();await load()}
 if(!data)return <p>Loading settings…</p>;
 const input="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3";
 return <div className="mx-auto max-w-7xl"><PageHeading eyebrow="Configuration" title="Settings" description="Manage shifts, operating rules, and Slack delivery."/>{message&&<p className="mb-5 rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</p>}<div className="grid gap-6 xl:grid-cols-2">
 <form onSubmit={addShift} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Clock3 className="text-orange-500"/><h2 className="text-lg font-bold">Shifts and coverage</h2></div><div className="mt-5 space-y-3">{data.shifts.map(s=><div key={s.id} className="flex justify-between rounded-xl bg-slate-50 p-4"><div><b>{s.name}</b><p className="text-sm text-slate-500">{s.startTime}–{s.endTime}</p></div><span className="text-sm text-slate-500">Minimum {s.staffingRules[0]?.minimumStaff??0}</span></div>)}</div><div className="mt-5 grid grid-cols-2 gap-3"><input required name="name" placeholder="Shift name" className={input}/><input required name="staff" type="number" min="0" placeholder="Minimum staff" className={input}/><input required name="start" type="time" className={input}/><input required name="end" type="time" className={input}/><input name="bilingual" type="number" min="0" defaultValue="0" className={input}/><button className="mt-2 flex items-center justify-center gap-2 rounded-xl bg-slate-950 font-bold text-white"><Plus className="h-4 w-4"/>Add shift</button></div></form>
 <form onSubmit={save} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Bell className="text-orange-500"/><h2 className="text-lg font-bold">Operations and Slack</h2></div><label className="mt-5 block text-sm font-semibold">Timezone<input name="timezone" defaultValue={data.settings.timezone} className={input}/></label><div className="grid grid-cols-2 gap-3"><label className="mt-4 block text-sm font-semibold">Post time<input name="postTime" type="time" defaultValue={data.settings.postTime} className={input}/></label><label className="mt-4 block text-sm font-semibold">Maximum consecutive days<input name="maxDays" type="number" min="1" max="7" defaultValue={data.settings.maxConsecutiveDays} className={input}/></label></div><label className="mt-4 block text-sm font-semibold">Slack channel ID<input name="channel" defaultValue={data.settings.slackChannelId} placeholder="C012ABC34" className={input}/></label><div className={`mt-4 rounded-xl p-4 text-sm ${data.slackConfigured?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-800"}`}>{data.slackConfigured?"Slack tokens are configured by the host.":"Slack tokens still need to be added to the hosting environment."}</div><label className="mt-4 flex gap-3 text-sm font-semibold"><input name="automation" type="checkbox" defaultChecked={data.settings.automationEnabled}/>Enable automatic daily posting</label><button className="mt-6 w-full rounded-xl bg-orange-500 px-5 py-3 font-bold text-white">Save settings</button></form></div></div>}
