"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { FormEvent, useEffect, useState } from "react";
import { Building2, CheckCircle2, Clock3, Plus, ShieldCheck, Trash2, Users } from "lucide-react";
import { PageHeading } from "@/components/ui/page-heading";

type Window = { id: string; dayOfWeek: number; startTime: string; endTime: string };
type Requirement = Window & { minimumStaff: number; minimumBilingual: number };
type Task = { id: string; name: string; icon: string; groupName: string | null; isLive: boolean; mode: "EVERYONE" | "FOCUS" | "SECONDARY"; defaultPriority: number; rotationOrder: number };
type Account = { id: string; name: string; code: string; active: boolean; operatingWindows: Window[]; coverageRequirements: Requirement[]; employeeCapabilities: { employeeId: string }[]; taskCategories: Task[] };
type Employee = { id: string; name: string };
type Shift = { id: string; name: string; startTime: string; endTime: string; staffingRules: { dayOfWeek: number; minimumStaff: number; minimumBilingual: number; isOverride: boolean }[] };
const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const input = "rounded-lg border border-slate-200 bg-white p-2 text-sm outline-none focus:border-orange-400 focus:ring-2 focus:ring-orange-100";

export default function OperationsPage() {
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [shifts, setShifts] = useState<Shift[]>([]);
  const [capacityDay, setCapacityDay] = useState(0);
  const [message, setMessage] = useState<{ text: string; error?: boolean } | null>(null);
  const [loading, setLoading] = useState(true);

  async function load() {
    const response = await fetch("/api/operations"); const body = await response.json();
    if (!response.ok) { setMessage({ text: body.error ?? "Operations could not be loaded.", error: true }); return; }
    setAccounts(body.accounts); setEmployees(body.employees); setShifts(body.shifts);
  }
  useEffect(() => { void load().finally(() => setLoading(false)); }, []);
  async function act(payload: Record<string, unknown>, success = "Operation settings saved.") { const response = await fetch("/api/operations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); setMessage({ text: response.ok ? success : body.error ?? "The change could not be saved.", error: !response.ok }); if (response.ok) await load(); return response.ok; }
  async function addAccount(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const value = new FormData(form); if (await act({ action: "createAccount", name: value.get("name"), code: value.get("code"), color: "blue" }, "Account added.")) form.reset(); }
  async function addWindow(event: FormEvent<HTMLFormElement>, accountId: string) { event.preventDefault(); const form = event.currentTarget; const value = new FormData(form); if (await act({ action: "addWindow", accountId, dayOfWeek: Number(value.get("day")), startTime: value.get("start"), endTime: value.get("end") }, "Service hours added.")) form.reset(); }
  async function addCoverage(event: FormEvent<HTMLFormElement>, accountId: string) { event.preventDefault(); const form = event.currentTarget; const value = new FormData(form); if (await act({ action: "upsertCoverage", accountId, dayOfWeek: Number(value.get("day")), startTime: value.get("start"), endTime: value.get("end"), minimumStaff: Number(value.get("staff")), minimumBilingual: Number(value.get("bilingual")) }, "Coverage requirement saved.")) form.reset(); }
  async function addTask(event: FormEvent<HTMLFormElement>, accountId: string) { event.preventDefault(); const form = event.currentTarget; const value = new FormData(form); const response = await fetch("/api/task-categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: value.get("name"), icon: value.get("icon") || "📌", groupName: value.get("group") || null, isLive: value.get("isLive") === "on", mode: value.get("mode"), defaultPriority: Number(value.get("priority")), rotationOrder: Number(value.get("rotationOrder")), accountId }) }); const body = await response.json(); setMessage({ text: response.ok ? "Task added." : body.error, error: !response.ok }); if (response.ok) { form.reset(); await load(); } }
  async function removeTask(id: string) { if (!confirm("Remove this task? Previous assignment history will be preserved.")) return; const response = await fetch("/api/task-categories", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); const body = await response.json(); setMessage({ text: response.ok ? "Task removed." : body.error, error: !response.ok }); if (response.ok) await load(); }
  async function saveCapacity(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const rules = shifts.map((shift) => ({ shiftId: shift.id, minimumStaff: Number(values.get(`${shift.id}-staff`)), minimumBilingual: Number(values.get(`${shift.id}-bilingual`)), isOverride: values.get(`${shift.id}-override`) === "on" })); const response = await fetch("/api/staffing-rules", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ dayOfWeek: capacityDay, rules }) }); const body = await response.json(); setMessage({ text: response.ok ? `${days[capacityDay]} staffing exceptions saved.` : body.error ?? "Staffing exceptions could not be saved.", error: !response.ok }); if (response.ok) await load(); }

  const activeAccounts = accounts.filter((account) => account.active);
  const readyAccounts = activeAccounts.filter((account) => account.operatingWindows.length && account.coverageRequirements.length && account.employeeCapabilities.length && account.taskCategories.length);

  return <div className="mx-auto max-w-7xl">
    <PageHeading eyebrow="Scheduling foundation" title="Operations" description="Define what each account needs before generating a schedule: service hours, required coverage, eligible agents, and daily tasks." />
    {message && <p role="status" className={`mb-5 rounded-xl p-4 text-sm font-semibold ${message.error ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}>{message.text}</p>}
    <section className="mb-6 grid gap-3 sm:grid-cols-3">
      <Stat label="Active accounts" value={activeAccounts.length} />
      <Stat label="Active agents" value={employees.length} />
      <Stat label="Ready for scheduling" value={`${readyAccounts.length} of ${activeAccounts.length}`} />
    </section>
    <section className="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <div className="flex items-center gap-3"><span className="rounded-xl bg-orange-50 p-3 text-orange-600"><Plus className="h-5 w-5" /></span><div><h2 className="font-bold">Add an account</h2><p className="text-sm text-slate-500">Create the account first, then configure its service rules below.</p></div></div>
      <form onSubmit={addAccount} className="mt-4 flex flex-wrap gap-3"><input required name="name" placeholder="Account name" className="min-w-56 flex-1 rounded-xl border border-slate-200 px-4 py-3" /><input required name="code" placeholder="Short code" className="w-48 rounded-xl border border-slate-200 px-4 py-3 uppercase" /><button className="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">Add account</button></form>
    </section>
    {loading ? <div className="rounded-2xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">Loading operation settings…</div> : <div className="space-y-6">{accounts.map((account) => <AccountCard key={account.id} account={account} employees={employees} act={act} addWindow={addWindow} addCoverage={addCoverage} addTask={addTask} removeTask={removeTask} />)}</div>}
    <details className="mt-6 rounded-2xl border border-slate-200 bg-white shadow-sm">
      <summary className="cursor-pointer list-none p-5"><div className="flex items-start gap-3"><span className="rounded-xl bg-slate-100 p-3 text-slate-600"><Users className="h-5 w-5" /></span><div><h2 className="font-bold">Advanced staffing exceptions</h2><p className="text-sm text-slate-500">Scheduling normally calculates staffing from account coverage. Use an exception only when a particular weekday and shift needs a fixed target.</p></div></div></summary>
      <form key={capacityDay} onSubmit={saveCapacity} className="border-t border-slate-100 p-5"><div className="flex flex-wrap gap-2">{days.map((day, index) => <button type="button" key={day} onClick={() => setCapacityDay(index)} className={`rounded-lg px-4 py-2 text-xs font-bold ${capacityDay === index ? "bg-orange-500 text-white" : "bg-slate-100 text-slate-600"}`}>{day.slice(0, 3)}</button>)}</div><div className="mt-4 grid gap-3 md:grid-cols-2">{shifts.map((shift) => { const rule = shift.staffingRules.find((item) => item.dayOfWeek === capacityDay); return <div key={`${shift.id}-${capacityDay}`} className="rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between"><div><b>{shift.name}</b><p className="text-xs text-slate-500">{shift.startTime}–{shift.endTime}</p></div><label className="flex items-center gap-2 text-xs font-bold"><input name={`${shift.id}-override`} type="checkbox" defaultChecked={rule?.isOverride ?? false} className="accent-orange-500" />Use exception</label></div><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-xs font-bold text-slate-500">Agents<input name={`${shift.id}-staff`} type="number" min="0" defaultValue={rule?.minimumStaff ?? 0} className={`mt-1 w-full ${input}`} /></label><label className="text-xs font-bold text-slate-500">Bilingual<input name={`${shift.id}-bilingual`} type="number" min="0" defaultValue={rule?.minimumBilingual ?? 0} className={`mt-1 w-full ${input}`} /></label></div><p className="mt-2 text-xs font-semibold text-slate-400">{rule?.isOverride ? "Exception active for this day" : "Automatic account coverage applies"}</p></div>; })}</div><button className="mt-4 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">Save staffing exceptions</button></form>
    </details>
  </div>;
}

function Stat({ label, value }: { label: string; value: string | number }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>; }

type CardProps = { account: Account; employees: Employee[]; act: (payload: Record<string, unknown>, success?: string) => Promise<boolean>; addWindow: (event: FormEvent<HTMLFormElement>, accountId: string) => Promise<void>; addCoverage: (event: FormEvent<HTMLFormElement>, accountId: string) => Promise<void>; addTask: (event: FormEvent<HTMLFormElement>, accountId: string) => Promise<void>; removeTask: (id: string) => Promise<void> };
function AccountCard({ account, employees, act, addWindow, addCoverage, addTask, removeTask }: CardProps) {
  const complete = account.operatingWindows.length > 0 && account.coverageRequirements.length > 0 && account.employeeCapabilities.length > 0 && account.taskCategories.length > 0;
  return <section className={`rounded-2xl border bg-white shadow-sm ${account.active ? "border-slate-200" : "border-slate-200 opacity-70"}`}>
    <header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div className="flex items-center gap-3"><span className="rounded-xl bg-orange-50 p-3 text-orange-600"><Building2 className="h-5 w-5" /></span><div><div className="flex items-center gap-2"><h2 className="font-bold">{account.name}</h2>{account.active && complete && <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700"><CheckCircle2 className="h-3 w-3" />Ready</span>}</div><p className="text-xs text-slate-500">{account.code} · {account.active ? "Included in scheduling" : "Not included in scheduling"}</p></div></div><button type="button" onClick={() => void act({ action: "updateAccount", id: account.id, name: account.name, code: account.code, active: !account.active }, account.active ? "Account deactivated." : "Account reactivated.")} className={`rounded-xl px-4 py-2 text-xs font-bold ${account.active ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}>{account.active ? "Deactivate" : "Reactivate"}</button></header>
    <div className="grid gap-6 p-5 lg:grid-cols-2">
      <Panel icon={<Clock3 className="h-5 w-5 text-blue-600" />} title="1. Service hours" description="Add every day and time period when this account operates.">
        <div className="max-h-56 space-y-2 overflow-auto">{account.operatingWindows.length ? account.operatingWindows.map((window) => <Row key={window.id} text={<><b>{days[window.dayOfWeek]}</b> · {window.startTime}–{window.endTime}</>} onRemove={() => void act({ action: "removeWindow", id: window.id }, "Service hours removed.")} label="Remove service hours" />) : <Empty text="No service hours configured." />}</div>
        <form onSubmit={(event) => addWindow(event, account.id)} className="mt-3 grid grid-cols-2 gap-2"><select name="day" aria-label="Service day" className={`col-span-2 ${input}`}>{days.map((day, index) => <option key={day} value={index}>{day}</option>)}</select><input required name="start" aria-label="Opening time" type="time" className={input} /><input required name="end" aria-label="Closing time" type="time" className={input} /><button className="col-span-2 rounded-lg bg-slate-950 p-2 text-xs font-bold text-white">Add service hours</button></form>
      </Panel>
      <Panel icon={<ShieldCheck className="h-5 w-5 text-violet-600" />} title="2. Required coverage" description="Set the minimum qualified agents needed within the service hours.">
        <div className="max-h-56 space-y-2 overflow-auto">{account.coverageRequirements.length ? account.coverageRequirements.map((rule) => <Row key={rule.id} text={<><b>{days[rule.dayOfWeek]}</b> · {rule.startTime}–{rule.endTime}<br /><span className="text-xs text-slate-500">{rule.minimumStaff} agent{rule.minimumStaff === 1 ? "" : "s"} · {rule.minimumBilingual} bilingual</span></>} onRemove={() => void act({ action: "removeCoverage", id: rule.id }, "Coverage requirement removed.")} label="Remove coverage requirement" />) : <Empty text="No coverage requirements configured." />}</div>
        <form onSubmit={(event) => addCoverage(event, account.id)} className="mt-3 grid grid-cols-2 gap-2"><select name="day" aria-label="Coverage day" className={`col-span-2 ${input}`}>{days.map((day, index) => <option key={day} value={index}>{day}</option>)}</select><input required name="start" aria-label="Coverage start" type="time" className={input} /><input required name="end" aria-label="Coverage end" type="time" className={input} /><label className="text-xs font-bold text-slate-500">Minimum agents<input required name="staff" type="number" min="0" defaultValue="1" className={`mt-1 w-full ${input}`} /></label><label className="text-xs font-bold text-slate-500">Bilingual agents<input required name="bilingual" type="number" min="0" defaultValue="0" className={`mt-1 w-full ${input}`} /></label><button className="col-span-2 rounded-lg bg-slate-950 p-2 text-xs font-bold text-white">Save coverage requirement</button></form>
      </Panel>
      <Panel icon={<Users className="h-5 w-5 text-emerald-600" />} title="3. Eligible team" description="Only selected agents can satisfy this account’s coverage."><div className="grid gap-2 sm:grid-cols-2">{employees.length ? employees.map((employee) => { const enabled = account.employeeCapabilities.some((item) => item.employeeId === employee.id); return <label key={employee.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-semibold"><input type="checkbox" checked={enabled} onChange={(event) => void act({ action: "setCapability", employeeId: employee.id, accountId: account.id, enabled: event.target.checked }, `${employee.name} eligibility updated.`)} className="accent-orange-500" />{employee.name}</label>; }) : <p className="text-xs text-slate-500">Add agents in Team before assigning eligibility.</p>}</div></Panel>
      <Panel title="4. Tasks" description="Everyone = shared by all; Focus = one primary owner rotated weekly; Secondary = distributed afterward.">
        <div className="max-h-56 space-y-2 overflow-auto">{account.taskCategories.length ? account.taskCategories.map((item) => <div key={item.id} className="flex items-start gap-2 rounded-xl bg-slate-50 p-3 text-sm"><div className="min-w-0 flex-1"><b>{item.icon} {item.name}</b><p className="text-xs text-slate-500">{item.groupName || "General"} · {item.mode === "EVERYONE" ? "everyone" : item.mode === "FOCUS" ? "weekly focus" : "secondary"} · P{item.defaultPriority}{item.mode === "FOCUS" ? ` · rotation ${item.rotationOrder}` : ""}{item.isLive ? " · live coverage" : ""}</p></div><button type="button" aria-label={`Remove ${item.name}`} onClick={() => void removeTask(item.id)} className="text-slate-400 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div>) : <Empty text="No tasks configured." />}</div>
        <form onSubmit={(event) => addTask(event, account.id)} className="mt-3 grid grid-cols-2 gap-2"><input name="icon" aria-label="Task icon" placeholder="📌" className={input} /><input required name="name" placeholder="Task name" className={input} /><input name="group" placeholder="Task group, e.g. Emails" className={`col-span-2 ${input}`} /><label className="text-xs font-bold text-slate-500">Assignment method<select name="mode" defaultValue="SECONDARY" className={`mt-1 w-full ${input}`}><option value="EVERYONE">Everyone</option><option value="FOCUS">Weekly focus</option><option value="SECONDARY">Secondary</option></select></label><label className="text-xs font-bold text-slate-500">Default priority<select name="priority" defaultValue="2" className={`mt-1 w-full ${input}`}><option value="1">Priority 1</option><option value="2">Priority 2</option></select></label><label className="text-xs font-bold text-slate-500">Rotation position<input name="rotationOrder" type="number" min="0" defaultValue="0" className={`mt-1 w-full ${input}`} /></label><label className="flex items-center gap-2 pt-5 text-xs font-bold"><input name="isLive" type="checkbox" className="accent-orange-500" />Requires live coverage</label><button className="col-span-2 rounded-lg bg-slate-950 p-2 text-xs font-bold text-white">Add task</button></form>
      </Panel>
    </div>
  </section>;
}
function Panel({ icon, title, description, children }: { icon?: React.ReactNode; title: string; description: string; children: React.ReactNode }) { return <div className="rounded-2xl border border-slate-200 p-4"><div className="mb-4 flex gap-3">{icon}<div><h3 className="text-sm font-bold">{title}</h3><p className="mt-1 text-xs text-slate-500">{description}</p></div></div>{children}</div>; }
function Row({ text, onRemove, label }: { text: React.ReactNode; onRemove: () => void; label: string }) { return <div className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm"><span>{text}</span><button type="button" aria-label={label} onClick={onRemove} className="text-slate-400 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl bg-amber-50 p-3 text-xs font-semibold text-amber-700">{text}</p>; }
