"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { FormEvent, useEffect, useState } from "react";
import { Building2, Plus, Trash2, Users } from "lucide-react";
import { PageHeading } from "@/components/ui/page-heading";

type Window = { id: string; dayOfWeek: number; startTime: string; endTime: string };
type Requirement = Window & { minimumStaff: number; minimumBilingual: number };
type Workstream = { id: string; name: string; icon: string; groupName: string | null; isLive: boolean; mode: "EVERYONE" | "FOCUS" | "SECONDARY"; defaultPriority: number };
type Account = { id: string; name: string; code: string; active: boolean; operatingWindows: Window[]; coverageRequirements: Requirement[]; employeeCapabilities: { employeeId: string }[]; taskCategories: Workstream[] };
type Employee = { id: string; name: string };
type Shift = { id: string; name: string; startTime: string; endTime: string; staffingRules: { dayOfWeek: number; minimumStaff: number; minimumBilingual: number }[] };
const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const input = "rounded-lg border border-slate-200 bg-white p-2 text-sm";

export default function OperationsPage() {
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [shifts, setShifts] = useState<Shift[]>([]);
  const [capacityDay, setCapacityDay] = useState(0);
  const [message, setMessage] = useState("");

  async function load() { const response = await fetch("/api/operations"); const body = await response.json(); setAccounts(body.accounts); setEmployees(body.employees); setShifts(body.shifts); }
  useEffect(() => { void load(); }, []);
  async function act(payload: Record<string, unknown>) { const response = await fetch("/api/operations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); setMessage(response.ok ? "Operation configuration saved." : body.error); if (response.ok) await load(); return response.ok; }
  async function addAccount(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const value = new FormData(form); if (await act({ action: "createAccount", name: value.get("name"), code: value.get("code"), color: "blue" })) form.reset(); }
  async function addWindow(event: FormEvent<HTMLFormElement>, accountId: string) { event.preventDefault(); const form = event.currentTarget; const value = new FormData(form); if (await act({ action: "addWindow", accountId, dayOfWeek: Number(value.get("day")), startTime: value.get("start"), endTime: value.get("end") })) form.reset(); }
  async function addCoverage(event: FormEvent<HTMLFormElement>, accountId: string) { event.preventDefault(); const form = event.currentTarget; const value = new FormData(form); if (await act({ action: "upsertCoverage", accountId, dayOfWeek: Number(value.get("day")), startTime: value.get("start"), endTime: value.get("end"), minimumStaff: Number(value.get("staff")), minimumBilingual: Number(value.get("bilingual")) })) form.reset(); }
  async function addWorkstream(event: FormEvent<HTMLFormElement>, accountId: string) { event.preventDefault(); const form = event.currentTarget; const value = new FormData(form); const response = await fetch("/api/task-categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: value.get("name"), icon: value.get("icon") || "📌", groupName: value.get("group") || null, isLive: value.get("isLive") === "on", mode: value.get("mode"), defaultPriority: Number(value.get("priority")), accountId }) }); const body = await response.json(); setMessage(response.ok ? "Workstream added." : body.error); if (response.ok) { form.reset(); await load(); } }
  async function removeWorkstream(id: string) { if (!confirm("Remove this workstream? Existing task history will be preserved.")) return; const response = await fetch("/api/task-categories", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); const body = await response.json(); setMessage(response.ok ? "Workstream removed." : body.error); if (response.ok) await load(); }
  async function saveCapacity(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const rules = shifts.map((shift) => ({ shiftId: shift.id, minimumStaff: Number(values.get(`${shift.id}-staff`)), minimumBilingual: Number(values.get(`${shift.id}-bilingual`)) })); const response = await fetch("/api/staffing-rules", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ dayOfWeek: capacityDay, rules }) }); const body = await response.json(); setMessage(response.ok ? "Team capacity saved." : body.error ?? "Team capacity could not be saved."); if (response.ok) await load(); }

  return <div className="mx-auto max-w-7xl">
    <PageHeading eyebrow="Single source of truth" title="Operations" description="Configure account hours, required coverage, team capacity, agent eligibility, and workstreams. The schedule follows these rules automatically." />
    {message && <p className="mb-5 rounded-xl bg-blue-50 p-4 text-sm font-semibold text-blue-700">{message}</p>}
    <section className="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <div className="flex items-start gap-3"><span className="rounded-xl bg-blue-50 p-3 text-blue-600"><Users className="h-5 w-5" /></span><div><h2 className="font-bold">Team capacity by shift</h2><p className="text-sm text-slate-500">This controls how many agents the schedule assigns. Account coverage below controls what service must remain covered.</p></div></div>
      <form onSubmit={saveCapacity} className="mt-5"><div className="flex flex-wrap gap-2">{days.map((day, index) => <button type="button" key={day} onClick={() => setCapacityDay(index)} className={`rounded-lg px-4 py-2 text-xs font-bold ${capacityDay === index ? "bg-orange-500 text-white" : "bg-slate-100 text-slate-600"}`}>{day.slice(0, 3)}</button>)}</div><div className="mt-4 grid gap-3 md:grid-cols-2">{shifts.map((shift) => { const rule = shift.staffingRules.find((item) => item.dayOfWeek === capacityDay); return <div key={shift.id} className="grid grid-cols-[1fr_110px_110px] items-end gap-3 rounded-xl bg-slate-50 p-4"><div><b>{shift.name}</b><p className="text-xs text-slate-500">{shift.startTime}–{shift.endTime}</p></div><label className="text-xs font-bold text-slate-500">Agents<input name={`${shift.id}-staff`} type="number" min="0" defaultValue={rule?.minimumStaff ?? 0} className={`mt-1 w-full ${input}`} /></label><label className="text-xs font-bold text-slate-500">Bilingual<input name={`${shift.id}-bilingual`} type="number" min="0" defaultValue={rule?.minimumBilingual ?? 0} className={`mt-1 w-full ${input}`} /></label></div>; })}</div><button className="mt-4 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">Save team capacity</button></form>
    </section>
    <form onSubmit={addAccount} className="mb-6 flex flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><input required name="name" placeholder="Account name" className="min-w-56 flex-1 rounded-xl border border-slate-200 px-4 py-3" /><input required name="code" placeholder="Short code" className="w-48 rounded-xl border border-slate-200 px-4 py-3" /><button className="flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 font-bold text-white"><Plus className="h-4 w-4" />Add account</button></form>
    <div className="space-y-6">{accounts.map((account) => <section key={account.id} className="rounded-2xl border border-slate-200 bg-white shadow-sm">
      <header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div className="flex items-center gap-3"><span className="rounded-xl bg-orange-50 p-3 text-orange-600"><Building2 className="h-5 w-5" /></span><div><h2 className="font-bold">{account.name}</h2><p className="text-xs text-slate-500">{account.code} · {account.active ? "Active" : "Inactive"}</p></div></div><button onClick={() => void act({ action: "updateAccount", id: account.id, name: account.name, code: account.code, active: !account.active })} className={`rounded-xl px-4 py-2 text-xs font-bold ${account.active ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}>{account.active ? "Deactivate" : "Reactivate"}</button></header>
      <div className="grid gap-6 p-5 xl:grid-cols-4">
        <div><h3 className="text-sm font-bold">Operating hours</h3><p className="mt-1 text-xs text-slate-500">Days and hours when this account operates.</p><div className="mt-3 space-y-2">{account.operatingWindows.map((window) => <div key={window.id} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm"><span><b>{days[window.dayOfWeek]}</b> · {window.startTime}–{window.endTime}</span><button aria-label="Remove operating window" onClick={() => void act({ action: "removeWindow", id: window.id })} className="text-slate-400 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div>)}</div><form onSubmit={(event) => addWindow(event, account.id)} className="mt-3 grid grid-cols-2 gap-2"><select name="day" className={`col-span-2 ${input}`}>{days.map((day, index) => <option key={day} value={index}>{day}</option>)}</select><input required name="start" type="time" className={input} /><input required name="end" type="time" className={input} /><button className="col-span-2 rounded-lg bg-slate-950 p-2 text-xs font-bold text-white">Add operating hours</button></form></div>
        <div><h3 className="text-sm font-bold">Service coverage</h3><p className="mt-1 text-xs text-slate-500">Minimum qualified agents required during each window.</p><div className="mt-3 space-y-2">{account.coverageRequirements.map((rule) => <div key={rule.id} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm"><span><b>{days[rule.dayOfWeek]}</b> {rule.startTime}–{rule.endTime}<br /><span className="text-xs text-slate-500">{rule.minimumStaff} agents · {rule.minimumBilingual} bilingual</span></span><button aria-label="Remove coverage rule" onClick={() => void act({ action: "removeCoverage", id: rule.id })} className="text-slate-400 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div>)}</div><form onSubmit={(event) => addCoverage(event, account.id)} className="mt-3 grid grid-cols-2 gap-2"><select name="day" className={`col-span-2 ${input}`}>{days.map((day, index) => <option key={day} value={index}>{day}</option>)}</select><input required name="start" type="time" className={input} /><input required name="end" type="time" className={input} /><input required name="staff" type="number" min="0" defaultValue="1" aria-label="Minimum agents" className={input} /><input required name="bilingual" type="number" min="0" defaultValue="0" aria-label="Minimum bilingual" className={input} /><button className="col-span-2 rounded-lg bg-slate-950 p-2 text-xs font-bold text-white">Save coverage window</button></form></div>
        <div><h3 className="text-sm font-bold">Eligible agents</h3><p className="mt-1 text-xs text-slate-500">Agents qualified to handle this account.</p><div className="mt-3 space-y-2">{employees.map((employee) => { const enabled = account.employeeCapabilities.some((item) => item.employeeId === employee.id); return <label key={employee.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-semibold"><input type="checkbox" checked={enabled} onChange={(event) => void act({ action: "setCapability", employeeId: employee.id, accountId: account.id, enabled: event.target.checked })} className="accent-orange-500" />{employee.name}</label>; })}</div></div>
        <div><h3 className="text-sm font-bold">Workstreams</h3><p className="mt-1 text-xs text-slate-500">Everyone = shared duty; Focus = one primary queue; Secondary = distributed afterward.</p><div className="mt-3 space-y-2">{account.taskCategories.map((item) => <div key={item.id} className="flex items-start gap-2 rounded-xl bg-slate-50 p-3 text-sm"><div className="min-w-0 flex-1"><b>{item.icon} {item.name}</b><p className="text-xs text-slate-500">{item.groupName || "General"} · {item.mode.toLowerCase()} · P{item.defaultPriority}{item.isLive ? " · continuous" : ""}</p></div><button aria-label={`Remove ${item.name}`} onClick={() => void removeWorkstream(item.id)} className="text-slate-400 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div>)}</div><form onSubmit={(event) => addWorkstream(event, account.id)} className="mt-3 grid grid-cols-2 gap-2"><input name="icon" placeholder="📌" className={input} /><input required name="name" placeholder="Workstream" className={input} /><input name="group" placeholder="Group, e.g. Emails" className={`col-span-2 ${input}`} /><select name="mode" defaultValue="SECONDARY" className={input}><option value="EVERYONE">Everyone</option><option value="FOCUS">Focus queue</option><option value="SECONDARY">Secondary</option></select><select name="priority" defaultValue="2" className={input}><option value="1">Priority 1</option><option value="2">Priority 2</option></select><label className="col-span-2 flex items-center gap-2 text-xs font-bold"><input name="isLive" type="checkbox" className="accent-orange-500" />Requires continuous coverage</label><button className="col-span-2 rounded-lg bg-slate-950 p-2 text-xs font-bold text-white">Add workstream</button></form></div>
      </div>
    </section>)}</div>
  </div>;
}
